### ISSUE TITLE
I managed to deploy only the "TransparentUpgradeableProxy".

### ISSUE THREAD

**Issue by johnnybegoode77** [PatrickAlphaC/smartcontract-upgrades-example#2]
I believe there was an error when I first deployed the contract.
After fixing the error, I managed to deploy only the "TransparentUpgradeableProxy" contract.

How to redeploy like it was the first deployment so that I could get
"Box", "ProxyAdmin" and "TransparentUpgradeableProxy" contracts.

Thank you!

**Comment by PatrickAlphaC** [comment]
I'm not sure I follow... 

I think it would be easiest just to redeploy everything. Thanks!
