### ISSUE TITLE
Where can we keep track of implmentation contracts? 

### ISSUE THREAD

**Issue by Ibby-debug** [PatrickAlphaC/smartcontract-upgrades-example#3]
If I'm understanding this correctly the `proxy contract` is the one responsible for creating `implementation contracts` using the `ProxyAdmin ` rules. However, I cannot see the proxy's contract code, all what we have is the implementation contract code (box.sol and box2.sol). What am I missing here?

**Comment by devjdeed** [comment]
Ok I found the explanation answer in the YouTube comments. 
<img width="653" alt="Proxy Explaination " src="https://user-images.githubusercontent.com/72482204/188250262-7dc9a6d8-ddd0-4e13-9e60-e306fccf8356.png">
